INSERT INTO COMMON_CODE (CODE_ID, NAME, SUPERIOR_CODE_ID, SORT_ORDER, USE_YN, REGISTERED_DATE, MODIFIED_DATE, REGISTRANT_GUID, MODIFIER_GUID, REMARKS) VALUES
  ('SKILL_CODE', '기술 스택', '0000', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('POSITION_CODE', '포지션', '0000', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('POSITION_LEVEL_CODE', '숙련도', '0000', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('PROJECT_RECRUIT_TYPE', '모집 유형', '0000', 4, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('PROJECT_PROGRESS_TYPE', '진행 방식', '0000', 5, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('PROJECT_RECRUIT_STATUS', '모집 상태', '0000', 6, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('PROJECT_APPROVAL_STATUS', '승인 상태', '0000', 7, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('POST_CATEGORY', '게시글 카테고리', '0000', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('REPORT_TYPE', '신고 유형', '0000', 9, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('NOTIFICATION_TYPE', '알림 유형', '0000', 10, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root'),
('REGION_CODE', '지역 코드', '0000', 11, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'Root');

INSERT INTO COMMON_CODE (CODE_ID, NAME, SUPERIOR_CODE_ID, SORT_ORDER, USE_YN, REGISTERED_DATE, MODIFIED_DATE, REGISTRANT_GUID, MODIFIER_GUID, REMARKS) VALUES
-- SKILL_CODE
('1001', 'Java', 'SKILL_CODE', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('1002', 'Spring', 'SKILL_CODE', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('1003', 'React', 'SKILL_CODE', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('1004', 'Node.js', 'SKILL_CODE', 4, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
-- POSITION_CODE
('2001', 'Backend', 'POSITION_CODE', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('2002', 'Frontend', 'POSITION_CODE', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('2003', 'Fullstack', 'POSITION_CODE', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('2004', 'Mobile', 'POSITION_CODE', 4, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
-- POSITION_LEVEL_CODE
('2101', '초급', 'POSITION_LEVEL_CODE', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('2102', '중급', 'POSITION_LEVEL_CODE', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('2103', '고급', 'POSITION_LEVEL_CODE', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
-- PROJECT_RECRUIT_TYPE
('3001', '일반모집', 'PROJECT_RECRUIT_TYPE', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('3002', '추가모집', 'PROJECT_RECRUIT_TYPE', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
-- PROJECT_PROGRESS_TYPE
('3101', '온라인', 'PROJECT_PROGRESS_TYPE', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('3102', '오프라인', 'PROJECT_PROGRESS_TYPE', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('3103', '온/오프라인 병행', 'PROJECT_PROGRESS_TYPE', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
-- PROJECT_RECRUIT_STATUS
('3201', '모집중', 'PROJECT_RECRUIT_STATUS', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('3202', '모집완료', 'PROJECT_RECRUIT_STATUS', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('3203', '모집대기', 'PROJECT_RECRUIT_STATUS', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('3204', '진행중', 'PROJECT_RECRUIT_STATUS', 4, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
-- PROJECT_APPROVAL_STATUS
('3301', '승인 대기', 'PROJECT_APPROVAL_STATUS', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('3302', '승인 완료', 'PROJECT_APPROVAL_STATUS', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('3303', '승인 거절', 'PROJECT_APPROVAL_STATUS', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
-- BOARD_CATEGORY
('4001', '자유게시판', 'BOARD_CATEGORY', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('4002', '질문', 'BOARD_CATEGORY', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('4003', '공지사항', 'BOARD_CATEGORY', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
-- REPORT_TYPE
('5001', '스팸/광고', 'REPORT_TYPE', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('5002', '욕설/비방', 'REPORT_TYPE', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('5003', '불법 콘텐츠', 'REPORT_TYPE', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
-- NOTIFICATION_TYPE
('6001', '프로젝트 지원 알림', 'NOTIFICATION_TYPE', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('6002', '프로젝트 승인 알림', 'NOTIFICATION_TYPE', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('6003', '댓글 알림', 'NOTIFICATION_TYPE', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', '');

-- 대분류 (Depth 1)
INSERT INTO COMMON_CODE (CODE_ID, NAME, SUPERIOR_CODE_ID, SORT_ORDER, USE_YN, REGISTERED_DATE, MODIFIED_DATE, REGISTRANT_GUID, MODIFIER_GUID, REMARKS) VALUES
  ('8100', '서울', 'REGION_CODE', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('8200', '경기', 'REGION_CODE', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('8300', '인천', 'REGION_CODE', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('8400', '부산', 'REGION_CODE', 4, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', '');

-- 서울 소분류 (Depth 2)
INSERT INTO COMMON_CODE (CODE_ID, NAME, SUPERIOR_CODE_ID, SORT_ORDER, USE_YN, REGISTERED_DATE, MODIFIED_DATE, REGISTRANT_GUID, MODIFIER_GUID, REMARKS) VALUES
  ('810001', '강남구', '8100', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810002', '강동구', '8100', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810003', '강북구', '8100', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810004', '강서구', '8100', 4, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810005', '관악구', '8100', 5, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810006', '광진구', '8100', 6, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810007', '구로구', '8100', 7, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810008', '금천구', '8100', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810009', '노원구', '8100', 9, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810010', '도봉구', '8100', 10, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810011', '동대문구', '8100', 11, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810012', '동작구', '8100', 12, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810013', '마포구', '8100', 13, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810014', '서대문구', '8100', 14, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810015', '서초구', '8100', 15, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810016', '성동구', '8100', 16, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810017', '성북구', '8100', 17, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810018', '송파구', '8100', 18, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810019', '양천구', '8100', 19, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810020', '영등포구', '8100', 20, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810021', '용산구', '8100', 21, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810022', '은평구', '8100', 22, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810023', '종로구', '8100', 23, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810024', '중구', '8100', 24, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('810025', '중랑구', '8100', 25, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', '');

-- 경기 소분류 (Depth 2)
INSERT INTO COMMON_CODE (CODE_ID, NAME, SUPERIOR_CODE_ID, SORT_ORDER, USE_YN, REGISTERED_DATE, MODIFIED_DATE, REGISTRANT_GUID, MODIFIER_GUID, REMARKS) VALUES
  ('820001', '수원시', '8200', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820002', '성남시', '8200', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820003', '고양시', '8200', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820004', '용인시', '8200', 4, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820005', '부천시', '8200', 5, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820006', '안산시', '8200', 6, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820007', '안양시', '8200', 7, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820008', '남양주시', '8200', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820009', '화성시', '8200', 9, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820010', '평택시', '8200', 10, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820011', '의정부시', '8200', 11, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820012', '시흥시', '8200', 12, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820013', '파주시', '8200', 13, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820014', '김포시', '8200', 14, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820015', '광명시', '8200', 15, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820016', '군포시', '8200', 16, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820017', '이천시', '8200', 17, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820018', '양주시', '8200', 18, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820019', '오산시', '8200', 19, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('820020', '구리시', '8200', 20, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', '');

-- 인천 소분류 (Depth 2)
INSERT INTO COMMON_CODE (CODE_ID, NAME, SUPERIOR_CODE_ID, SORT_ORDER, USE_YN, REGISTERED_DATE, MODIFIED_DATE, REGISTRANT_GUID, MODIFIER_GUID, REMARKS) VALUES
  ('830001', '중구', '8300', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('830002', '동구', '8300', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('830003', '미추홀구', '8300', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('830004', '연수구', '8300', 4, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('830005', '남동구', '8300', 5, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('830006', '부평구', '8300', 6, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('830007', '계양구', '8300', 7, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('830008', '서구', '8300', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', '');

-- 부산 소분류 (Depth 2)
INSERT INTO COMMON_CODE (CODE_ID, NAME, SUPERIOR_CODE_ID, SORT_ORDER, USE_YN, REGISTERED_DATE, MODIFIED_DATE, REGISTRANT_GUID, MODIFIER_GUID, REMARKS) VALUES
  ('840001', '해운대구', '8400', 1, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('840002', '수영구', '8400', 2, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('840003', '남구', '8400', 3, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('840004', '동래구', '8400', 4, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('840005', '부산진구', '8400', 5, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('840006', '사하구', '8400', 6, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('840007', '북구', '8400', 7, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('840008', '사상구', '8400', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', ''),
('840009', '강서구', '8400', 9, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', '');

