spring:
  application:
    name: DevHub

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
    open-in-view: false

  sql:
    init:
      mode: always
      data-locations: classpath:sql/init-data.sql

server:
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: devhub-backend