-- =====================================================
-- USERS
-- =====================================================
CREATE TABLE USERS
(
  USER_GUID       VARCHAR(32) PRIMARY KEY,
  MANNER_DEGREE   DOUBLE NOT NULL,
  BLOCK_END_DATE  TIMESTAMP(6),
  LAST_LOGIN_DATE TIMESTAMP(6),
  MODIFIED_DATE   TIMESTAMP(6),
  REGISTERED_DATE TIMESTAMP(6),
  INTRODUCTION    VARCHAR(500),
  BLOCKED         VARCHAR(1) NOT NULL CHECK (BLOCKED IN ('N','Y')),
  DELETED         VARCHAR(1) NOT NULL CHECK (DELETED IN ('N','Y')),
  EMAIL           VARCHAR(255) NOT NULL UNIQUE,
  OAUTH_ID        VARCHAR(255),
  PASSWORD        VARCHAR(255) NOT NULL,
  USERNAME        VARCHAR(255),
  PROVIDER        VARCHAR(20) CHECK (PROVIDER IN ('EMAIL','GITHUB','GOOGLE','KAKAO')),
  USER_ROLE       VARCHAR(10) NOT NULL CHECK (USER_ROLE IN ('ADMIN','USER')),
  FILE_GUID       VARCHAR(255)
);

-- =====================================================
-- ATTACHMENT_FILE
-- =====================================================
CREATE TABLE ATTACHMENT_FILE
(
  FILE_GUID       VARCHAR(32) PRIMARY KEY,
  SIZE            BIGINT NOT NULL,
  MODIFIED_DATE   TIMESTAMP(6),
  REGISTERED_DATE TIMESTAMP(6),
  EXTENSION_NAME  VARCHAR(255) NOT NULL,
  ORIGINAL_NAME   VARCHAR(255) NOT NULL,
  PATH            VARCHAR(255) NOT NULL
);

-- =====================================================
-- APPLICATION_FORM
-- =====================================================
CREATE TABLE APPLICATION_FORM
(
  APPLICATION_FORM_GUID VARCHAR(32) PRIMARY KEY,
  MODIFIED_DATE         TIMESTAMP(6),
  REGISTERED_DATE       TIMESTAMP(6),
  CUSTOM_YN             VARCHAR(1) NOT NULL CHECK (CUSTOM_YN IN ('N','Y')),
  HELP_TEXT             VARCHAR(255) NOT NULL,
  TITLE                 VARCHAR(255) NOT NULL,
  TYPE_CD               VARCHAR(255) NOT NULL,
  USE_YN                VARCHAR(1) NOT NULL CHECK (USE_YN IN ('N','Y'))
);

CREATE TABLE APPLICATION_FORM_ITEM
(
  FORM_ITEM_GUID VARCHAR(32) PRIMARY KEY,
  FORM_GUID      VARCHAR(32) NOT NULL,
  CONTENT        VARCHAR(255) NOT NULL,
  CONSTRAINT FK_FORM_ITEM_FORM FOREIGN KEY (FORM_GUID)
    REFERENCES APPLICATION_FORM(APPLICATION_FORM_GUID)
);

-- =====================================================
-- PROJECT
-- =====================================================
CREATE TABLE PROJECT
(
  PROJECT_GUID           VARCHAR(32) PRIMARY KEY,
  USER_GUID              VARCHAR(32) NOT NULL,
  PROGRESS_END_DATE      DATE NOT NULL,
  PROGRESS_START_DATE    DATE NOT NULL,
  RECRUITMENT_END_DATE   DATE NOT NULL,
  RECRUITMENT_START_DATE DATE NOT NULL,
  PROGRESS_REGION_CD     VARCHAR(10),
  PROGRESS_TYPE_CD       VARCHAR(10) NOT NULL,
  RECRUITMENT_TYPE_CD    VARCHAR(10) NOT NULL,
  ATTACHMENT_FILE_GUID   VARCHAR(32),
  IMAGE_FILE_GUID        VARCHAR(32),
  CAPACITY_CLOSED_YN     VARCHAR(1) NOT NULL CHECK (CAPACITY_CLOSED_YN IN ('N','Y')),
  CATEGORY               VARCHAR(255) NOT NULL,
  CONTENT                VARCHAR(255) NOT NULL,
  DELETE_YN              VARCHAR(1) NOT NULL CHECK (DELETE_YN IN ('N','Y')),
  TITLE                  VARCHAR(255) NOT NULL,
  USERNAME               VARCHAR(255) NOT NULL,
  CONSTRAINT FK_PROJECT_USER FOREIGN KEY (USER_GUID)
    REFERENCES USERS(USER_GUID),
  CONSTRAINT FK_PROJECT_ATTACHMENT FOREIGN KEY (ATTACHMENT_FILE_GUID)
    REFERENCES ATTACHMENT_FILE(FILE_GUID)
);

CREATE TABLE PROJECT_REQUIREMENT
(
  PROJECT_REQUIREMENT_GUID VARCHAR(32) PRIMARY KEY,
  PROJECT_GUID             VARCHAR(32) NOT NULL,
  POSITION_CD              VARCHAR(10) NOT NULL,
  LEVEL_CD                 VARCHAR(10) NOT NULL,
  CAPACITY                 INTEGER NOT NULL,
  CONSTRAINT FK_REQUIREMENT_PROJECT FOREIGN KEY (PROJECT_GUID)
    REFERENCES PROJECT(PROJECT_GUID)
);

CREATE TABLE PROJECT_SKILL
(
  PROJECT_SKILL_GUID VARCHAR(32) PRIMARY KEY,
  PROJECT_GUID       VARCHAR(32) NOT NULL,
  SKILL_CD           VARCHAR(10) NOT NULL,
  CONSTRAINT FK_PROJECT_SKILL_PROJECT FOREIGN KEY (PROJECT_GUID)
    REFERENCES PROJECT(PROJECT_GUID)
);

CREATE TABLE PROJECT_LIKE
(
  PROJECT_LIKE_GUID VARCHAR(32) PRIMARY KEY,
  PROJECT_GUID      VARCHAR(32) NOT NULL,
  USER_GUID         VARCHAR(32) NOT NULL,
  CONSTRAINT FK_PROJECT_LIKE_PROJECT FOREIGN KEY (PROJECT_GUID)
    REFERENCES PROJECT(PROJECT_GUID),
  CONSTRAINT FK_PROJECT_LIKE_USER FOREIGN KEY (USER_GUID)
    REFERENCES USERS(USER_GUID)
);

-- =====================================================
-- PROJECT_APPLICATION
-- =====================================================
CREATE TABLE PROJECT_APPLICATION
(
  APPLICATION_GUID VARCHAR(32) PRIMARY KEY,
  PROJECT_GUID     VARCHAR(32) NOT NULL,
  APPLICANT_GUID   VARCHAR(32) NOT NULL,
  APPROVER_GUID    VARCHAR(32),
  REQUIREMENT_GUID VARCHAR(32) NOT NULL,
  STATUS_CD        VARCHAR(255) NOT NULL,
  CANCEL_YN        VARCHAR(1) NOT NULL CHECK (CANCEL_YN IN ('N','Y')),
  CONSTRAINT FK_APPLICATION_PROJECT FOREIGN KEY (PROJECT_GUID)
    REFERENCES PROJECT(PROJECT_GUID),
  CONSTRAINT FK_APPLICATION_USER FOREIGN KEY (APPLICANT_GUID)
    REFERENCES USERS(USER_GUID)
);

CREATE TABLE PROJECT_APPLICATION_FORM
(
  PROJECT_APPLICATION_FORM_GUID VARCHAR(32) PRIMARY KEY,
  APPLICATION_FORM_GUID         VARCHAR(32) NOT NULL,
  PROJECT_GUID                  VARCHAR(32) NOT NULL,
  CONSTRAINT FK_PAF_FORM FOREIGN KEY (APPLICATION_FORM_GUID)
    REFERENCES APPLICATION_FORM(APPLICATION_FORM_GUID),
  CONSTRAINT FK_PAF_PROJECT FOREIGN KEY (PROJECT_GUID)
    REFERENCES PROJECT(PROJECT_GUID)
);

CREATE TABLE PROJECT_APPLICATION_ANSWER
(
  APPLICATION_ANSWER_GUID       VARCHAR(32) PRIMARY KEY,
  APPLICATION_FORM_GUID         VARCHAR(32) NOT NULL,
  APPLICATION_GUID              VARCHAR(32) NOT NULL,
  PROJECT_APPLICATION_FORM_GUID VARCHAR(32) NOT NULL,
  PROJECT_GUID                  VARCHAR(32) NOT NULL,
  FILE_GUID                     VARCHAR(32),
  CONTENT                       VARCHAR(255) NOT NULL,
  CONSTRAINT FK_ANSWER_APPLICATION FOREIGN KEY (APPLICATION_GUID)
    REFERENCES PROJECT_APPLICATION(APPLICATION_GUID)
);

-- =====================================================
-- BOARD
-- =====================================================
CREATE TABLE BOARD
(
  BOARD_GUID  VARCHAR(32) PRIMARY KEY,
  USER_GUID   VARCHAR(32) NOT NULL,
  CATEGORY_CD VARCHAR(255) NOT NULL,
  CONTENT     VARCHAR(255) NOT NULL,
  TITLE       VARCHAR(255) NOT NULL,
  VIEW_COUNT  INTEGER,
  CONSTRAINT FK_BOARD_USER FOREIGN KEY (USER_GUID)
    REFERENCES USERS(USER_GUID)
);

CREATE TABLE COMMENT
(
  COMMENT_GUID VARCHAR(32) PRIMARY KEY,
  BOARD_GUID   VARCHAR(32) NOT NULL,
  USER_GUID    VARCHAR(32) NOT NULL,
  CONTENT      VARCHAR(255) NOT NULL,
  CONSTRAINT FK_COMMENT_BOARD FOREIGN KEY (BOARD_GUID)
    REFERENCES BOARD(BOARD_GUID),
  CONSTRAINT FK_COMMENT_USER FOREIGN KEY (USER_GUID)
    REFERENCES USERS(USER_GUID)
);

CREATE TABLE BOARD_LIKE
(
  BOARD_LIKE_GUID VARCHAR(32) PRIMARY KEY,
  BOARD_GUID      VARCHAR(32) NOT NULL,
  USER_GUID       VARCHAR(32) NOT NULL,
  CONSTRAINT FK_BOARD_LIKE_BOARD FOREIGN KEY (BOARD_GUID)
    REFERENCES BOARD(BOARD_GUID),
  CONSTRAINT FK_BOARD_LIKE_USER FOREIGN KEY (USER_GUID)
    REFERENCES USERS(USER_GUID)
);

-- =====================================================
-- REFRESH_TOKEN / VERIFICATIONS
-- =====================================================
-- MySQL에서는 AUTO_INCREMENT 사용
CREATE TABLE REFRESH_TOKEN
(
  ID        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TOKEN     VARCHAR(500) NOT NULL,
  USER_GUID VARCHAR(255) NOT NULL UNIQUE,
  CONSTRAINT FK_REFRESH_USER FOREIGN KEY (USER_GUID)
    REFERENCES USERS(USER_GUID)
);

CREATE TABLE VERIFICATIONS
(
  ID                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CODE              VARCHAR(255),
  TARGET_VALUE      VARCHAR(255) NOT NULL,
  VERIFIED          VARCHAR(1) NOT NULL CHECK (VERIFIED IN ('N','Y')),
  VERIFICATION_TYPE VARCHAR(10) NOT NULL CHECK (VERIFICATION_TYPE IN ('EMAIL','OTP','SMS')),
  EXPIRED_AT        TIMESTAMP(6)
);

-- =====================================================
-- COMMON_CODE
-- =====================================================
CREATE TABLE COMMON_CODE
(
  CODE_ID          VARCHAR(255) PRIMARY KEY,
  NAME             VARCHAR(255) NOT NULL,
  SUPERIOR_CODE_ID VARCHAR(255),
  SORT_ORDER       VARCHAR(255) NOT NULL,
  USE_YN           VARCHAR(1) NOT NULL CHECK (USE_YN IN ('N','Y')),
  CONSTRAINT FK_COMMON_PARENT FOREIGN KEY (SUPERIOR_CODE_ID)
    REFERENCES COMMON_CODE(CODE_ID)
);

-- =====================================================
-- USER_POSITION / USER_SKILL / USER_REVIEW
-- =====================================================
CREATE TABLE USER_POSITION
(
  USER__POSITION_GUID VARCHAR(255) PRIMARY KEY,
  USER_GUID           VARCHAR(255) NOT NULL,
  POSITION_CD         VARCHAR(10) NOT NULL,
  CONSTRAINT FK_USER_POSITION_USER FOREIGN KEY (USER_GUID)
    REFERENCES USERS(USER_GUID),
  CONSTRAINT UK_USER_POSITION UNIQUE (USER_GUID, POSITION_CD)
);

CREATE TABLE USER_SKILL
(
  USER_SKILL_GUID VARCHAR(255) PRIMARY KEY,
  USER_GUID       VARCHAR(255) NOT NULL,
  SKILL_CD        VARCHAR(10) NOT NULL,
  CONSTRAINT FK_USER_SKILL_USER FOREIGN KEY (USER_GUID)
    REFERENCES USERS(USER_GUID),
  CONSTRAINT UK_USER_SKILL UNIQUE (USER_GUID, SKILL_CD)
);

CREATE TABLE USER_REVIEW
(
  USER_REVIEW_GUID VARCHAR(32) PRIMARY KEY,
  PROJECT_GUID     VARCHAR(32) NOT NULL,
  REVIEWEE         VARCHAR(255) NOT NULL,
  REVIEWER         VARCHAR(255) NOT NULL,
  SCORE            INTEGER NOT NULL,
  CONSTRAINT FK_REVIEW_PROJECT FOREIGN KEY (PROJECT_GUID)
    REFERENCES PROJECT(PROJECT_GUID)
);

-- =====================================================
-- REPORT / NOTIFICATION / BANNER
-- =====================================================
CREATE TABLE REPORT
(
  REPORT_GUID  VARCHAR(32) PRIMARY KEY,
  BOARD_GUID   VARCHAR(255) NOT NULL,
  CATEGORY_CD  VARCHAR(255) NOT NULL,
  COMMENT_GUID VARCHAR(255) NOT NULL,
  PROCESS_YN   VARCHAR(1) NOT NULL CHECK (PROCESS_YN IN ('N','Y')),
  REASON       VARCHAR(255) NOT NULL
);

CREATE TABLE NOTIFICATION
(
  NOTIFICATION_GUID VARCHAR(32) PRIMARY KEY,
  TYPE_CD           VARCHAR(10) NOT NULL,
  IMAGE_GUID        VARCHAR(32) NOT NULL,
  RECEIVER          VARCHAR(32) NOT NULL,
  CHECKED           VARCHAR(1) NOT NULL CHECK (CHECKED IN ('N','Y')),
  CONTENT           VARCHAR(255) NOT NULL
);

CREATE TABLE BANNER
(
  BANNER_GUID            VARCHAR(32) PRIMARY KEY,
  IMAGE_GUID             VARCHAR(32) NOT NULL,
  DESCRIPTION            VARCHAR(255) NOT NULL,
  IS_MAIN_BANNER         VARCHAR(1) NOT NULL CHECK (IS_MAIN_BANNER IN ('N','Y')),
  TITLE                  VARCHAR(255) NOT NULL,
  LINK                   VARCHAR(255) NOT NULL,
  USED                   VARCHAR(1) NOT NULL CHECK (USED IN ('N','Y')),
  PUBLICATION_START_DATE TIMESTAMP(6) NOT NULL,
  PUBLICATION_END_DATE   TIMESTAMP(6) NOT NULL
);

-- =====================================================
-- TERMS / TERMS_AGREEMENT
-- =====================================================
CREATE TABLE TERMS
(
  TERMS_GUID  VARCHAR(32) PRIMARY KEY,
  CONTENT     VARCHAR(255) NOT NULL,
  DELETE_YN   VARCHAR(1) NOT NULL CHECK (DELETE_YN IN ('N','Y')),
  NAME        VARCHAR(255) NOT NULL,
  REQUIRED_YN VARCHAR(1) NOT NULL CHECK (REQUIRED_YN IN ('N','Y')),
  USE_YN      VARCHAR(1) NOT NULL CHECK (USE_YN IN ('N','Y'))
);

CREATE TABLE TERMS_AGREEMENT
(
  TERMS_AGREEMENT_GUID VARCHAR(32) PRIMARY KEY,
  TERMS_GUID           VARCHAR(255) NOT NULL,
  USER_GUID            VARCHAR(255) NOT NULL,
  AGREEMENT_YN         VARCHAR(1) NOT NULL CHECK (AGREEMENT_YN IN ('N','Y')),
  CONSTRAINT FK_TERMS_AGREE_TERMS FOREIGN KEY (TERMS_GUID)
    REFERENCES TERMS(TERMS_GUID),
  CONSTRAINT FK_TERMS_AGREE_USER FOREIGN KEY (USER_GUID)
    REFERENCES USERS(USER_GUID)
);