name: Backend CI/CD

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  PROJECT: devhub-b
  TARGET_ENV: dev

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build Application
        run: ./gradlew clean build -x test

      - name: Generate Build Tag
        run: |
          DATE=$(date +%Y%m%d)
          BUILD_TAG="${PROJECT}-${DATE}-${GITHUB_RUN_NUMBER}"
          echo "BUILD_TAG=${BUILD_TAG,,}" >> $GITHUB_ENV

      - name: Set Image Name
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${PROJECT}-${TARGET_ENV}"
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        run: |
          docker build \
            -t ${IMAGE_NAME}:${BUILD_TAG} \
            .

      - name: Docker Push
        run: |
          docker push ${IMAGE_NAME}:${BUILD_TAG}

      - name: Checkout Infra Repository
        uses: actions/checkout@v4
        with:
          repository: TeamDevhub/devhub-infra
          ref: dev
          path: infra

      - name: Verify Deployment File
        run: |
          test -f infra/k8s/dev/devhub-b/deployment.yml

      - name: Update Deployment Image
        run: |
          DEPLOY_FILE="infra/k8s/dev/devhub-b/deployment.yml"

          sed -i \
            "s#image: .*#image: ${IMAGE_NAME}:${BUILD_TAG}#g" \
            ${DEPLOY_FILE}

          echo "Updated deployment.yml"
          grep image: ${DEPLOY_FILE}

      - name: Commit And Push Infra Changes
        run: |

          cd infra

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add k8s/dev/devhub-b/deployment.yml

          git commit \
            -m "[CI] Update backend image to ${BUILD_TAG}" \
            || echo "No changes"

          git push origin dev

      - name: Print Result
        run: |
          echo "================================="
          echo "Backend Build Success"
          echo "Image : ${IMAGE_NAME}:${BUILD_TAG}"
          echo "================================="
